### ISSUE TITLE
EFCore : Unable to add more than one child at a time if child's PK relies on it being autoincremented by database

### ISSUE THREAD

**Issue by amarden** [jtheisen/reconciler#1]
First, I wanted to thank you for making this library, I really missed GraphDiff when I moved to dotnet core and appreciate your work on this. 

I may be doing something wrong (as I am just trying to replicate what I do in GraphDiff), but I noticed when I try to add more than one child to to a parent in a single update I get an error indicating that the instance of what I am updating is already tracked with the same key value. This is due to me submitting two children with the same PK of 0 because the PK of the objects do not get set until they are written to the database. 

This may be related to one of the items in already your ideas.md file (in which case apologies for being annoying). 

Anyway, thanks again for all your work on this.

**Comment by jtheisen** [comment]
Thanks for the kind words.

Indeed since I don't usually use database-generated keys myself, I didn't think of them at all.

I'll look into it.

**Comment by jtheisen** [comment]
I'm struggling to reproduce this. Can you give me the two relevant model classes and the reconcile call expression? Also, is the exception coming on SaveChanges?

If that's not possible, can you confirm that we're not talking about a many-to-many relationship?

**Comment by amarden** [comment]
Not talking about a many to many relationship:

Models are:
`
  public partial class Tracking
    {
        public Tracking()
        {
            TrackingContact = new HashSet<TrackingContact>();
        }

        public int TrackingId { get; set; }
        public string First { get; set; }
        public string Second { get; set; }

  public ICollection<TrackingContact> TrackingContact { get; set; }
}

 public partial class TrackingContact
    {
        public int TrackingContactId { get; set; }
        public int TrackingId { get; set; }
        public DateTime? Response{ get; set; }
        public DateTime? Updated { get; set; }

        public Tracking Tracking { get; set; }
    }
`

The Reconcile code is: `_context.Reconcile(updatedTracking, x => x.WithMany(c => c.TrackingContact));` Where updatedTracking is of Type Tracking.

The error occurs when trying to execute the Reconcile line (before SaveChanges) when I am adding at least two new TrackingContacts each of which has a TrackingContactId of 0 (since I am relying on the database to provide the Id on Insert). 

The innermost exception is: "System.InvalidOperationException : The instance of entity type 'TrackingContact' cannot be tracked because another instance with the same key value for {'TrackingContactId'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached."

Thank you for the quick response!

**Comment by jtheisen** [comment]
Is the `updatedTracking` detached, or attached or a different context than `_context`?

**Comment by amarden** [comment]
I believe its detached.

**Comment by miriamblumenstein** [comment]
Reproduced and hopefully fixed this. Please let us know if this works for you.

**Comment by amarden** [comment]
Works as expected. Thank you!
