### ISSUE TITLE
Entity state mismatch - Causing Cannot insert explicit value for identity column

### ISSUE THREAD

**Issue by chukwu** [jtheisen/reconciler#11]
I have a one to many relationship between **Services (Parent Record)  -----> ServiceTranslations(Child List).**

When I have more than one translations and I update one child/translation, **reconciler** for some reason sees this Entity.State as Added instead of modified thereby causing

**Cannot insert explicit value for identity column in table 'ServiceTranslation' when IDENTITY_INSERT is set to OFF.**

My code is below:
`await _appDbContext.ReconcileAsync(services, e => e.WithMany(m => m.Translations));`

Debug is below
![errorScreen](https://user-images.githubusercontent.com/1703024/67272725-1f796300-f4ce-11e9-9e9f-7214691569f6.JPG)

I was able to track it on **SaveChangesAsync()** override method and tracing the entity state after **reconcileAsync** is executed

**Comment by jtheisen** [comment]
I have to admit I don't use database-generated keys myself, so Reconciler hasn't been tested with those. I will put in a warning about that in the readme.

This does sound weird though. I will test this later and may come back with further questions.

**Comment by chukwu** [comment]
I think this could be due to my .net core upgrade to **.net core 3.0** or **EF core 3.0**.
Similar code as mentioned above works on my earlier **.net core 2.2** projects. Could it be, there is a breaking change on .net core 3.0 that this library is yet to support for **EF core 3.0**?

The plugin doesn't seem to recognise the entity state as modified for multiple collection. It sets the first record as **ADDED** and others as **MODIFIED**. Weired!!!

**Comment by chukwu** [comment]
I’m highly anticipating a fix for this. Any timeline for this fix?

**Comment by chukwu** [comment]
Hi,
I found the cause. I cloned your repo just to see whats up.
In my case it is one thing leading to another that causes this bug.
**QUERYFILTER!**

**NOTE: This isn't an EF core 3.0 issue neither is .net core 3.**

I have a global query filter to filter Translations based on users language preference.
You need to add **ignoreQueryFilters** when loading children of an entity.

This fix would also help users that have soft delete feature on their model.
I believe this would expedite your update and point you to the right direction for an update. I'll study deeper into your logic and see if I can make a pull request.


I'll appreciate if you make this changes soonest.
Thanks.

**Comment by chukwu** [comment]
You've been silent for awhile.
I extracted your library and fixed the issue for my project locally.
All i need to do was to add modify below in EFCore.cs 
from
`var query = db.Set<E>().Where(where);`
to
`var query = db.Set<E>().IgnoreQueryFilters().Where(where);`

You may do same and publish for EF6 and EFCore in your source file. Until then, i'll keep my local copy until you update this.
Cheers!!!

**Comment by jtheisen** [comment]
Five years after my abandonment I had a new look at Reconciler and fixed a number of issues. I'm not certain to what extent this issue still applies, therefore I'm closing this now.
