### ISSUE TITLE
Foreign key violation during insert

### ISSUE THREAD

**Issue by gubellinif** [jtheisen/reconciler#13]
Does Reconciler support the insertion of entities with a nesting level greater than 2? In my case, for example, I have a Master -> Detail_Level_1 -> Detail_Level_2 structure, where Detail_Level_2 has a foreign key reference to Detail_Level_1, and Detail_Level_1 has a foreign key reference to Master. When I add an entry to Detail_Level_1 and Detail_Level_2 to the dbContext, Entity Framework tries to insert the Detail_Level_2 entry first generating a foreign key violation.
Thanks.

**Comment by jtheisen** [comment]
It should work, yes.

I just added a new test (the last one in the suite) and that appears to work.

Some more questions:

- EF Core or EF6?
- Can you clarify on what exactly is there before and what you reconcile to? (You can also add or modify the test in the suite; note that the new test is easier to understand than the previous ones.)

**Comment by gubellinif** [comment]
Hello jtheisen,
thank you for the prompt response.
I've looked at the test code, and it has some differences from my case. The identifiers are not known in advance because they are not Strings but Integers generated by the database. Below is an excerpt of how I modified the model definitions and the directives given to the ModelBuilder.

class Star
{
    public int Id { get; set; }
    public string Name { get; set; }
    public ICollection<Planet> Planets { get; set; } = new List<Planet>();
}
class Planet
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int StarId { get; set; }
    public Star Star { get; set; }
    public ICollection<Moon> Moons { get; set; } = new List<Moon>();
}
class Moon
{
    public int Id { get; set; }
    public string Name { get; set; }
    public Planet Planet { get; set; }
    public int PlanetId { get; set; }
}
..
protected override void OnModelCreating(ModelBuilder builder)
{
    builder.Entity<Address>().HasOne(a => a.Image).WithOne();
    builder.Entity<PersonTag>().HasOne(t => t.Payload).WithOne();
    builder.Entity<Star>().HasKey(s => s.Id);
    builder.Entity<Planet>().HasKey(p => p.Id);
    builder.Entity<Planet>().HasOne(p => p.Star).WithMany(s => s.Planets).HasForeignKey(p => p.StarId);
    builder.Entity<Moon>().HasKey(m => m.Id);
    builder.Entity<Moon>().HasOne(m => m.Planet).WithMany(p => p.Moons).HasForeignKey(m => m.PlanetId);
}

Furthermore, within the TestGraph method, the SaveGraph method is executed on the Target object, with the effect of populating the Ids of Planet and Moon. When the Reconcile method is executed, all the graph Ids have already been populated. Below are the changes I made to the TestGraph method.

void TestGraph<E>(E original, E target, Action<ExtentBuilder<E>> extent, out E reloadedTarget, out E reloadedUpdate)
    where E : class
{
    //SaveGraph(target);
    //reloadedTarget = new Context().LoadExtent(target, extent);
    reloadedTarget = target;
    ClearDb();
    SaveGraph(original);
    {
        var db = new Context();
        var attachedEntity = db.Reconcile(target, extent);
        //var entries = db.ChangeTracker.Entries().Select(e => new EntityWithState { Entry = e }).ToArray();
        db.SaveChanges();
    }
    reloadedUpdate = new Context().LoadExtent(target, extent);
    new Context().Normalize(original, extent);
    new Context().Normalize(reloadedTarget, extent);
    new Context().Normalize(reloadedUpdate, extent);
}

With these modifications, the Reconcile method uses a Target that has not been previously processed, and when it comes to SaveChanges, the ChangeTracker has the following state, where it can be observed that the Foreign Keys (FK) are populated with zeros. In the test case, I used an in-memory database, which does not generate exceptions, but using the SqlServer database, I believe you can reproduce the FK Violation issue discussed.

Moon {Id: 1} Added
  Id: 1 PK
  Name: 'deimos'
  PlanetId: 0 FK
  Planet: <null>
Moon {Id: 2} Added
  Id: 2 PK
  Name: 'phobos'
  PlanetId: 0 FK
  Planet: <null>
Planet {Id: 1} Added
  Id: 1 PK
  Name: 'mars'
  StarId: 1 FK
  Moons: []
  Star: {Id: 1}
Star {Id: 1} Unchanged
  Id: 1 PK
  Name: 'sun'
  Planets: [{Id: 1}]

I remain available if you need any further details.
Thank you.

**Comment by jtheisen** [comment]
I now know why this doesn't work. It won't work in all cases where entities with database-generated keys are inserted that have dependent entities inserted at the same time.

I don't use database-generated keys myself, hence I didn't properly test this.

I think I can fix it though, maybe I get to it on the weekend.

**Comment by gubellinif** [comment]
Hello jtheisen,
in my tests, I managed to handle this case by modifying the ReconcileAsync method of the ReconciliationExtensions class with the following change.

if (isNewEntity)
           {
               attachedEntity = db.Add(templateEntity).Entity;
               return attachedEntity;
               //attachedEntity = db.AddEntity(templateEntity);
           }

This way, the graph navigation is stopped at the first new Entity, and the handling of foreign keys is left to the ChangeTracker. I'm not sure if this modification introduces regressions, consider it a suggestion for your verification.
Thank you.

**Comment by jtheisen** [comment]
It's been a while but this should now be sorted out.

Unfortunately, the problem was a bit more tricky: Entities below the one being added may already exist (so you can't just add everything below it too). Also, I ran into more unrelated issues that I wanted fixing as well before I make another release.
